CREATE SEQUENCE manufacturer_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE customer_seq START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE rental_seq START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE equipment_seq START WITH 1 INCREMENT BY 1;
